version: "3.8"
services:
    frontend:
        build: ./frontend/
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/app/src
        environment:
            - REACT_APP_NAME=matlistanv2
    backend:
        build: ./backend/
        ports:
            - "3001:3001"
        volumes:
            - ./backend:/app/
        environment:
            - REACT_APP_NAME=backend
        env_file:
            - ./.env
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: development
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080