# Generated by Django 4.0.4 on 2022-05-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredienser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livsmedel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.livsmedel')),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=50)),
                ('instruktioner', models.TextField(blank=True, max_length=500)),
                ('portioner', models.FloatField(default=1)),
                ('livsmedel', models.ManyToManyField(through='backend.Ingredienser', to='backend.livsmedel')),
            ],
        ),
        migrations.AddField(
            model_name='ingredienser',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recept'),
        ),
    ]
