# Generated by Django 4.0.4 on 2022-05-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_ingredienser_recept_ingredienser_recept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GramPerUnit', models.FloatField(default=100)),
                ('liter', models.FloatField(blank=True, verbose_name=1)),
                ('DL', models.FloatField(blank=True, verbose_name=100)),
                ('CL', models.FloatField(blank=True, verbose_name=100)),
                ('ML', models.FloatField(blank=True, verbose_name=100)),
            ],
        ),
    ]
