# Generated by Django 4.0.4 on 2022-05-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='units',
            name='CL',
        ),
        migrations.RemoveField(
            model_name='units',
            name='DL',
        ),
        migrations.RemoveField(
            model_name='units',
            name='GramPerUnit',
        ),
        migrations.RemoveField(
            model_name='units',
            name='ML',
        ),
        migrations.RemoveField(
            model_name='units',
            name='liter',
        ),
        migrations.AddField(
            model_name='ingredienser',
            name='grams',
            field=models.FloatField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='units',
            name='clInGrams',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='units',
            name='dlInGrams',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='units',
            name='grams',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.CASCADE, to='backend.ingredienser'),
        ),
        migrations.AddField(
            model_name='units',
            name='literInGrams',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='units',
            name='mlInGrams',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
