# Generated by Django 4.0.4 on 2022-05-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_ingredienser_id_remove_units_cl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='grams',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='livsmedel',
        ),
        migrations.DeleteModel(
            name='Ingredienser',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
