# Generated by Django 4.0.4 on 2022-05-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_units_grams_remove_recept_livsmedel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredienser',
            fields=[
                ('ingrediens_id', models.AutoField(primary_key=True, serialize=False)),
                ('gram', models.FloatField(default=100)),
                ('livsmedel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.livsmedel')),
            ],
        ),
        migrations.AddField(
            model_name='recept',
            name='livsmedel',
            field=models.ManyToManyField(through='backend.Ingredienser', to='backend.livsmedel'),
        ),
        migrations.AddField(
            model_name='ingredienser',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recept'),
        ),
    ]
