# Generated by Django 4.0.4 on 2022-05-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_ingredienser_recept_livsmedel_ingredienser_recept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredienser',
            old_name='gram',
            new_name='Unit',
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literPer100g', models.FloatField(default=0)),
                ('dlPer100g', models.FloatField(default=0)),
                ('mlPer100g', models.FloatField(default=0)),
                ('clPer100g', models.FloatField(default=0)),
                ('Livsmedel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.livsmedel')),
            ],
        ),
    ]
