# Generated by Django 4.0.4 on 2022-05-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_gram_ingredienser_unit_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienser',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienser', to='backend.recept'),
        ),
    ]
