# Generated by Django 4.0.4 on 2022-05-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_ingredienser_recept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredienser',
            old_name='Unit',
            new_name='gram',
        ),
    ]
