# Generated by Django 4.0.4 on 2022-05-30 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_livsmedel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livsmedel',
            name='author',
        ),
        migrations.AddField(
            model_name='recept',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
