# Generated by Django 4.0.4 on 2022-05-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
